$primary_paletteKeyColor = 657990
$secondary_paletteKeyColor = 717882
$tertiary_paletteKeyColor = 8e748f
$neutral_paletteKeyColor = 777779
$neutral_variant_paletteKeyColor = 74777d
$background = 121315
$onBackground = e3e2e4
$surface = 121315
$surfaceDim = 121315
$surfaceBright = 39393b
$surfaceContainerLowest = 0d0e10
$surfaceContainerLow = 1b1c1d
$surfaceContainer = 1f2021
$surfaceContainerHigh = 292a2c
$surfaceContainerHighest = 343536
$onSurface = e3e2e4
$surfaceVariant = 43474c
$onSurfaceVariant = c4c6cd
$inverseSurface = e3e2e4
$inverseOnSurface = 303032
$outline = 8e9197
$outlineVariant = 43474c
$shadow = 000000
$scrim = 000000
$surfaceTint = b4c8e2
$primary = b4c8e2
$onPrimary = 1e3246
$primaryContainer = 7e93aa
$onPrimaryContainer = 001223
$inversePrimary = 4c6076
$secondary = c0c7d2
$onSecondary = 2a313a
$secondaryContainer = 404751
$onSecondaryContainer = aeb6c1
$tertiary = dbbddb
$onTertiary = 3e2940
$tertiaryContainer = a388a4
$onTertiaryContainer = 000000
$error = ffb4ab
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryFixed = d0e4ff
$primaryFixedDim = b4c8e2
$onPrimaryFixed = 061d30
$onPrimaryFixedVariant = 35485d
$secondaryFixed = dce3ee
$secondaryFixedDim = c0c7d2
$onSecondaryFixed = 151c24
$onSecondaryFixedVariant = 404751
$tertiaryFixed = f8d9f8
$tertiaryFixedDim = dbbddb
$onTertiaryFixed = 27142a
$onTertiaryFixedVariant = 563f58
$term0 = 343434
$term1 = 8383ff
$term2 = 44def5
$term3 = 75fcdd
$term4 = 85afd0
$term5 = 91a8ee
$term6 = 8dd2f4
$term7 = ccdcd6
$term8 = ac9fa9
$term9 = a29eff
$term10 = 89ecff
$term11 = c9fff3
$term12 = aac4d7
$term13 = adbdf8
$term14 = aae3ff
$term15 = ffffff
$rosewater = f4f0fa
$flamingo = dfe0f5
$pink = d1dcff
$mauve = 9ec1ff
$red = 9ab1ff
$maroon = b0bcf1
$peach = e0c2f9
$yellow = d0f9f4
$green = b8e6ff
$teal = c0e4ff
$sky = bbdfff
$sapphire = 95cdff
$blue = 89c1ff
$lavender = adcfff
$klink = 468cca
$klinkSelection = 458cca
$kvisited = 4a7fdb
$kvisitedSelection = 497fdb
$knegative = 607eff
$knegativeSelection = 607eff
$kneutral = c794ff
$kneutralSelection = c794ff
$kpositive = 00b6ef
$kpositiveSelection = 00b6ef
$text = e3e2e4
$subtext1 = c4c6cd
$subtext0 = 8e9197
$overlay2 = 7c7e84
$overlay1 = 696b6f
$overlay0 = 57595d
$surface2 = 47484c
$surface1 = 36373a
$surface0 = 242527
$base = 121315
$mantle = 121315
$crust = 111214
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
