general {
    layout = scrolling

    allow_tearing = false  # Allows `immediate` window rule to work

    gaps_workspaces = $workspaceGaps
    gaps_in = $windowGapsIn
    gaps_out = $windowGapsOut
    border_size = $windowBorderSize

    col.active_border = $activeWindowBorderColour
    col.inactive_border = $inactiveWindowBorderColour
}

scrolling {
    # The default width of a new window column (0.1 to 1.0)
    column_width = 0.5

    # When a window is focused, should the layout move to bring it into view?
    follow_focus = true

    # 0 = center the column, 1 = fit the column to the screen
    focus_fit_method = 0
}
